// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxrukkxkwlfstjxkyrqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cnVra3hrd2xmc3RqeGt5cnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzc3NzMsImV4cCI6MjA2MTYxMzc3M30.bGy7NPeoGww86gh9efjsaYFHDzi9OGU-uwxbuEWJW5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);